In case of RedHat defaults for the kdc config and the kdc database pointing to the same directory (/var/kerberos/krb5kdc)
If this happens following error ocures:

Error: Could not find dependency File[krb5-kdc-database-dir] for Exec[create_krb5kdc_principal] at /opt/puppet/modules/kerberos/manifests/kdc/master.pp:52

Because: File[$kdc_database_dir] already exists ( via the requirement in base.pp File[$kdc_conf_dir] )
	the dependency krb5-kdc-database-dir will not be fulfillable

But the real requirement for create_krb5kdc_principal is not the existing krb5-kdc-database-dir (which is actually the database itself)
but it should be the directory in which the database is created.